spring:
  #jsp
  mvc:
    view: 
      prefix: /WEB-INF/views/
      suffix: .jsp
  #jdbc 설정
  datasource:
    url: jdbc:mysql://localhost:3306/mango?autoReconnect=true
    username: root
    password: koreait2020
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 88a081241234cfacbedef7018ac451316f3
            client-secret: 88a081241234cfacbedef7018ac451316f3
          
          facebook:
            client-id: 419794055964381
            client-secret: c3d47da2bbed4060d827a6031caee649
   
custom: 
  oauth2: 
    kakao: 
      client-id: 88a081241234cfacbedef7018ac451316f3
      client-secret: jpXULoEzrasfawegsqYXlRLyyOHn2i60q 
    naver: 
      client-id: SeVHVvgislUv0RMrdBMM
      client-secret: ctPXW7bWwk
      
mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  type-aliases-package: com.koreait.mango.model 
  
#Tomcat
server: 
  port: 8090