spring:
  profiles:
    active: dev
  thymeleaf:
    check-template-location: true
    prefix: classpath:views/
    suffix: .html
    mode: HTML
    cache: false   
      
  #jdbc 설정
  datasource:
    url: jdbc:mysql://localhost:3306/mango?autoReconnect=true
    username: root
    password: koreait2020
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          google:            
            client-id: 본인 google client-id
            client-secret: 본인 google client-secret

          facebook:            
            client-id: 본인 facebook client-id
            client-secret: 본인 facebook client-secret
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 30MB
      location: D:/home/mango #윈도우에서 테스트할 때는 정확한 드라이브 값까지 줘야 함.
      #location: /home/mango 리눅스 서버에 저장하고 싶은 경로로 변경하면 됩니다.
custom: 
  oauth2: 
    kakao:
      client-id: 본인 kakao client-id
      client-secret: 본인 kakao client-secret
    naver:
      client-id: 본인 naver client-id
      client-secret: 본인 naver client-secret
      
mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  type-aliases-package: com.koreait.mango.model 

logging:
  config: classpath:logback-${spring.profiles.active}.xml
  
#Tomcat
server: 
  port: 8090
  
# java -jar -Dspring.profiles.active=prod    